"""Regenerates the `TEST.Fixture` dataset that the tests read.

The fixture is committed rather than built during the test run, so that it can
be inspected, diffed and pointed at as a worked example of the layout. This
script is how it was produced, and re-running it must leave the tree unchanged:

    .venv/bin/python tests/data/build_test_fixture.py
    git status --short tests/data

Every file it writes goes through this package's own writers wherever one
exists, so the fixture cannot claim a shape the library does not produce.

The fixture deliberately includes the awkward cases: a page with nothing but an
image and a transcription, a page that no split mentions, a split that names a
page which is not on disk, an image variant, and an alternative splits file.
"""

import json
import shutil
from datetime import datetime
from pathlib import Path

import cv2
import numpy as np

from musicorpus.coco import CocoBbox, CocoDatasetMetadata, CocoImageMetadata, CocoLicense
from musicorpus.image_subdivisions import ImageSubdivisions
from musicorpus.layout import Layout
from musicorpus.manifest import MusicorpusManifest
from musicorpus.page_metadata import PageMetadata
from musicorpus.splits import Splits

HERE = Path(__file__).parent
DATASET = HERE / "TEST.Fixture"

CREATED_AT = datetime(2026, 3, 5, 10, 16, 37)

MUSICXML = """<?xml version="1.0" encoding="UTF-8"?>
<score-partwise version="4.0">
  <part-list>
    <score-part id="P1"><part-name>Music</part-name></score-part>
  </part-list>
  <part id="P1">
    <measure number="1">
      <attributes>
        <divisions>1</divisions>
        <key><fifths>0</fifths></key>
        <time><beats>4</beats><beat-type>4</beat-type></time>
        <clef><sign>G</sign><line>2</line></clef>
      </attributes>
      <note>
        <pitch><step>C</step><octave>4</octave></pitch>
        <duration>4</duration><type>whole</type>
      </note>
    </measure>
  </part>
</score-partwise>
"""

KERN = """**kern
*clefG2
*k[]
*M4/4
1c
*-
"""


def write_image(path: Path, width: int, height: int) -> None:
    """A real JPEG, small but decodable, so image tests are not built on a lie."""
    image = np.full((height, width, 3), 255, dtype=np.uint8)
    image[height // 2 : height // 2 + 2, :, :] = 0  # a staff-line-ish stripe
    path.parent.mkdir(parents=True, exist_ok=True)
    assert cv2.imwrite(str(path), image), f"could not write {path}"


def write_sample(folder: Path, width: int, height: int, kern: bool = False) -> None:
    """The files a page or a subdivision carries."""
    folder.mkdir(parents=True, exist_ok=True)
    write_image(folder / "image.jpg", width, height)
    (folder / "transcription.musicxml").write_text(MUSICXML)
    if kern:
        (folder / "transcription.krn").write_text(KERN)


def page_metadata(page_name: str) -> PageMetadata:
    return PageMetadata(
        file_name=Path("TEST.Fixture") / page_name / "image.jpg",
        institution_name="Test Library",
        institution_rism_siglum="CZ-Tl",
        institution_local_siglum="TL",
        shelfmark="TL 1234",
        rism_id_number=None,
        date="1780",
        page_number=1,
        page_size=(210, 297),
        dpi=300,
        scribal_data=None,
        link="https://example.org/source",
        title_description="A test page",
        author="Anonymous",
        author_date=None,
        genre_form="sonata",
        notation="CWMN",
        notation_detailed=None,
        notation_complexity="polyphonic",
        production="printed",
        production_detailed=None,
        clarity="perfect",
        systems="grand-staff",
    )


def build() -> None:
    if DATASET.exists():
        shutil.rmtree(DATASET)
    DATASET.mkdir(parents=True)

    # === dataset-level files ===

    MusicorpusManifest(
        musicorpus_version="1.0",
        full_institution_name="Test Institution",
        short_institution_name="TEST",
        institution_url="https://example.org",
        full_dataset_name="MusiCorpus Test Fixture",
        short_dataset_name="Fixture",
        dataset_url="https://example.org/fixture",
        dataset_version="1.0",
        created_at=CREATED_AT,
        author_emails=["someone@example.org", "someone-else@example.org"],
    ).write_to_file(DATASET / "musicorpus.json")

    (DATASET / "README.md").write_text(
        "# MusiCorpus Test Fixture\n"
        "\n"
        "A tiny synthetic dataset used by this repository's tests. It is not real\n"
        "data — the images are blank rectangles and the transcriptions hold a\n"
        "single whole note — but its structure is exactly what the MusiCorpus\n"
        "specification asks for, so it doubles as a worked example of the layout.\n"
        "\n"
        "It is generated by `tests/data/build_test_fixture.py`.\n"
        "\n"
        "\n"
        "## Splits\n"
        "\n"
        "`splits.json` is a plain train/validation/test division. It deliberately\n"
        "does not cover every page: `page-outside-splits` is in no split, which\n"
        "the specification permits. `splits.alternative.json` covers the same\n"
        "pages differently and adds a `holdout` set.\n"
    )
    (DATASET / "LICENSE.txt").write_text(
        "This fixture contains no real data and is released under the same terms\n"
        "as the repository that holds it.\n"
    )

    # === splits ===

    Splits(
        train=["page-full", "page-minimal"],
        validation=["page-images-only"],
        test=["page-missing-from-disk"],
    ).write_to_file(DATASET / "splits.json", run_assertions=False)

    Splits(
        train=["page-full"],
        validation=["page-minimal"],
        test=["page-images-only"],
        holdout=["page-outside-splits"],
    ).write_to_file(DATASET / "splits.alternative.json", run_assertions=False)

    # === page-full: every optional file, both subdivision kinds ===

    page = DATASET / "page-full"
    write_sample(page, width=64, height=96, kern=True)
    write_image(page / "image.distorted.jpg", 64, 96)
    page_metadata("page-full").write_to_file(page / "metadata.json")

    staff_bboxes = {"1": CocoBbox(4, 8, 56, 16), "2": CocoBbox(4, 40, 56, 16)}
    grandstaff_bboxes = {"1-2": CocoBbox(4, 8, 56, 48)}
    ImageSubdivisions(
        staves=staff_bboxes,
        grandstaves=grandstaff_bboxes,
        systems={},
    ).write_to(page / "subdivisions.image.json")

    Layout(
        dataset_metadata=CocoDatasetMetadata(
            version="1.0",
            description="TEST.Fixture",
            contributor="Test Institution",
            url="https://example.org/fixture",
            date_created=CREATED_AT,
        ),
        image_metadata=CocoImageMetadata(
            width=64,
            height=96,
            file_name="TEST.Fixture/page-full/image.jpg",
            date_captured=CREATED_AT,
        ),
        image_license=CocoLicense(name="CC BY 4.0", url="https://example.org/license"),
        staves=list(staff_bboxes.values()),
        empty_staves=[],
        grandstaves=list(grandstaff_bboxes.values()),
        systems=[],
        staff_measures=[],
        grandstaff_measures=[],
        system_measures=[],
    ).write_to_file(page / "layout.json")

    for name in staff_bboxes:
        write_sample(page / "Staves" / name, width=56, height=16, kern=True)
    for name in grandstaff_bboxes:
        write_sample(page / "Grandstaves" / name, width=56, height=48)

    # === page-minimal: an image and a transcription, nothing else ===

    write_sample(DATASET / "page-minimal", width=64, height=96)

    # === page-images-only: an image, no transcription, a PNG rather than a JPEG ===

    images_only = DATASET / "page-images-only"
    images_only.mkdir()
    write_image(images_only / "image.png", 64, 96)

    # === page-outside-splits: on disk, named by no split in splits.json ===

    write_sample(DATASET / "page-outside-splits", width=64, height=96)

    # === a folder in the root that is not a dataset at all ===

    other = HERE / "not-a-dataset"
    other.mkdir(exist_ok=True)
    (other / "README.md").write_text(
        "Deliberately not a MusiCorpus dataset: it holds no musicorpus.json,\n"
        "so `Dataset.find_all` must skip it.\n"
    )

    print(f"wrote {DATASET}")
    print(f"  {sum(1 for _ in DATASET.rglob('*') if _.is_file())} files")


if __name__ == "__main__":
    build()
    # a sanity check that what was written reads back
    from musicorpus import Dataset

    dataset = Dataset.load(DATASET)
    print(f"  manifest: {dataset.manifest.full_dataset_name}")
    print(f"  pages:    {dataset.page_names}")
    print(f"  splits:   {list(dataset.splits().split_names())}")
    manifest_json = json.loads((DATASET / "musicorpus.json").read_text())
    print(f"  json ok:  musicorpus_version {manifest_json['musicorpus_version']}")
